In [52]:
import numpy as np
import pandas as pd

In [53]:
df = pd.read_csv("./data/students_info.csv", index_col="STD_ID")
df = df[~df.index.duplicated()]
df

,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),Образование,Дата выдачи,Что именно закончил
STD_ID,,,,,,,,,,
99136,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
99112,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО"
99109,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
99125,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ"""
100676,М,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,СР,2012-06-29 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
...,...,...,...,...,...,...,...,...,...,...
100678,Ж,СТ,NaN,БП,Д,31.05.01,Лечебное дело,СР,2013-06-21 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
100663,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,СР,2013-06-27 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
191630,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,СР,2014-05-31 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
191625,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN
194978,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5104 entries, 99136 to 194978
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Пол                          5103 non-null   object
 1   Статус                       5103 non-null   object
 2   Дата выпуска                 455 non-null    object
 3   Категория обучения           5103 non-null   object
 4   Форма обучения               5103 non-null   object
 5   Шифр                         5103 non-null   object
 6   направление (специальность)  5103 non-null   object
 7   Образование                  4913 non-null   object
 8   Дата выдачи                  4878 non-null   object
 9   Что именно закончил          4913 non-null   object
dtypes: object(10)
memory usage: 438.6+ KB

In [55]:
df["Статус"].value_counts()

Статус
СТ     4648
ВЫП     455
Name: count, dtype: int64

In [56]:
df.query("Пол == 'М' and Статус == 'СТ'")["направление (специальность)"].value_counts()

направление (специальность)
Лечебное дело                                                                256
Стоматология                                                                 186
Юриспруденция                                                                173
Строительство                                                                140
Теплоэнергетика и теплотехника                                               102
Педагогическое образование                                                    79
Агроинженерия                                                                 76
Эксплуатация транспортно-технологических машин и комплексов                   76
Менеджмент                                                                    75
Информатика и вычислительная техника                                          69
Конструирование и технология электронных средств                              66
Конструкторско-технологическое обеспечение машиностроительных производств     61
Педагогическое образование (с двумя профилями подготовки)                     44
Лесное дело                                                                   37
Прикладная математика и информатика                                           30
Экономика                                                                     30
Зоотехния                                                                     29
Радиотехника                                                                  29
Лингвистика                                                                   27
Журналистика                                                                  27
Землеустройство и кадастры                                                    26
Управление персоналом                                                         26
История                                                                       25
Электроника и наноэлектроника                                                 24
Архитектура                                                                   24
Фармация                                                                      24
Фундаментальная и прикладная химия                                            16
Технология художественной обработки материалов                                16
Мехатроника и робототехника                                                   15
Агрономия                                                                     15
Экология и природопользование                                                 14
Государственное и муниципальное управление                                    14
Психология                                                                    12
Дизайн                                                                        12
География                                                                     11
Технология производства и переработки сельскохозяйственной продукции          10
Биология                                                                      10
Культурология                                                                 10
Философия                                                                      8
Дизайн архитектурной среды                                                     8
Филология                                                                      5
Психолого-педагогическое образование                                           4
Специальное (дефектологическое) образование                                    1
Name: count, dtype: int64

In [57]:
df.query("Пол == 'Ж' and Статус == 'СТ'")["направление (специальность)"].value_counts()

направление (специальность)
Лечебное дело                                                                490
Педагогическое образование (с двумя профилями подготовки)                    249
Юриспруденция                                                                219
Стоматология                                                                 218
Педагогическое образование                                                   174
Экономика                                                                    132
Специальное (дефектологическое) образование                                  112
Лингвистика                                                                   86
Журналистика                                                                  81
Менеджмент                                                                    81
Фармация                                                                      68
Психология                                                                    59
Дизайн                                                                        55
Дизайн архитектурной среды                                                    54
Архитектура                                                                   49
Филология                                                                     48
Технология производства и переработки сельскохозяйственной продукции          48
Строительство                                                                 41
Управление персоналом                                                         39
Землеустройство и кадастры                                                    35
Зоотехния                                                                     34
Биология                                                                      32
Фундаментальная и прикладная химия                                            27
Агрономия                                                                     26
Психолого-педагогическое образование                                          25
Технология художественной обработки материалов                                25
Культурология                                                                 25
Государственное и муниципальное управление                                    24
География                                                                     20
История                                                                       19
Конструкторско-технологическое обеспечение машиностроительных производств     17
Экология и природопользование                                                 14
Конструирование и технология электронных средств                              12
Философия                                                                     11
Лесное дело                                                                   11
Электроника и наноэлектроника                                                  9
Информатика и вычислительная техника                                           8
Теплоэнергетика и теплотехника                                                 8
Сестринское дело                                                               7
Агроинженерия                                                                  5
Радиотехника                                                                   5
Прикладная математика и информатика                                            3
Эксплуатация транспортно-технологических машин и комплексов                    1
Name: count, dtype: int64

In [58]:
df[df.isna().all(axis=1)]

,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),Образование,Дата выдачи,Что именно закончил
STD_ID,,,,,,,,,,
92222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
df["направление (специальность)"].unique().shape

(45,)

In [60]:
df["Пол"].value_counts()

Пол
Ж    3015
М    2088
Name: count, dtype: int64